add smoketest

diff --git a/.github/workflows/app1.yaml b/.github/workflows/app1.yaml
--- a/.github/workflows/app1.yaml
+++ b/.github/workflows/app1.yaml
@@ -10,6 +10,10 @@ on:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}/app1
+  TEST_TAG: app1:test
+  CONTEXT: src/docker-images/app1
+  TEST_HOST_PORT: 8081
+  TEST_CONTAINER_PORT: 8081
 
 permissions:
   contents: read
@@ -20,6 +24,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images#publishing-images-to-github-packages
       - name: Checkout
         uses: actions/checkout@v5
 
@@ -36,11 +41,45 @@ jobs:
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
-      - name: Build and push Docker image
+      # https://docs.docker.com/build/ci/github-actions/test-before-push/
+      - name: Build and export to Docker
+        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
+        with:
+          context: ${{ env.CONTEXT }}
+          load: true
+          tags: ${{ env.TEST_TAG }}
+
+      - name: Test
+        run: |
+          set -e
+          trap "docker rm -f app1-test || true" EXIT
+
+          docker run -d \
+            -p ${{ env.TEST_HOST_PORT }}:${{ env.TEST_CONTAINER_PORT }} \
+            --name app1-test \
+            -e PREFIX=apptest \
+            -e PORT=${{ env.TEST_CONTAINER_PORT }} \
+            ${{ env.TEST_TAG }}
+
+          echo "Waiting for service to respond..."
+          for i in {1..15}; do
+            if curl -f http://localhost:${{ env.TEST_HOST_PORT }}/apptest/; then
+              echo "Service is up"
+              break
+            fi
+            sleep 2
+          done
+
+          # Final check (fail CI if service is not up)
+          curl -f http://localhost:${{ env.TEST_HOST_PORT }}/apptest/
+
+          echo "Smoke test passed!"
+
+      - name: Push Docker image
         id: push
         uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
         with:
-          context: src/docker-images/app1
+          context: ${{ env.CONTEXT }}
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
